### ISSUE TITLE
Customize book cover

### ISSUE THREAD

**Issue by giswqs** [mayconfmelo/min-book#4]
Thank you for creating this nice book template. I would like to use it. I am new to typst. Could you please let me know how I can customized the book cover background color and the pattern image? I did not find that information in the manual. Thanks. 

![Image](https://github.com/user-attachments/assets/02d6cc8f-3654-4f86-a345-3873d57726a0)

**Comment by mayconfmelo** [comment]
Thank you very much! And also thanks for your interest in _min-book_.

The automatic cover generation currently act only as a simple "placeholder" for writers that do not have the time and/or knowledge to create a book cover; for this reason, it does not offer any customization — but I will try to add this in the next update.

**Comment by mayconfmelo** [comment]
The custom cover creation is an advanced feature, so if you have any questions about this process or about the code I provided as `cover.typ`, feel free to ask.

**Comment by giswqs** [comment]
Thank you very much for the detailed instructions! That's very helpful! I will create my own `frame.svg` and then use your `cover.typ` to create the book. 

I just discovered typst yesterday and have created a [book chapter](https://github.com/opengeos/geospatial-dataviz-python/blob/main/data-viz.pdf) using MyST and typst. 

I plan to convert my [website](https://geog-312.gishub.org/) to book using typst. Your book template will be a big time saver. Thank you.

**Comment by mayconfmelo** [comment]
Typst is awesome indeed. And surely the content of your website will be a great test for _min-book_ performance in extensive books!

If you succeed to create your custom cover, please give me a feedback to close this issue.

**Comment by giswqs** [comment]
Will do. Thanks.

**Comment by giswqs** [comment]
How do I change the paper size to US Letter? Adding this does not work. 

![Image](https://github.com/user-attachments/assets/e44387d0-24cb-4e18-95c2-854bda84d5d3)

**Comment by giswqs** [comment]
I have several questions regarding customization. Thank you.

1. How to indent subsections in table of content? For example, level-2 headings should be indented after level01 headings.
2. How to add a color to text with a hyperlink? Currently, regiular text and hyperlinked text are both shown in black color.
3. How to make headings occupy one line instead of two lines?
4. How to remove the indentation before code blocks?



You can see my typ settings below:

<details>
<summary>Click to expand</summary>

```yml
#import "@preview/min-book:1.0.0": (
  book, note, horizontalrule, hr, blockquote, appendices, annexes
)

// Display inline code in a small box
// that retains the correct baseline.
#show raw.where(block: false): box.with(
  fill: luma(240),
  inset: (x: 3pt, y: 0pt),
  outset: (y: 3pt),
  radius: 2pt,
)

// Display block code in a larger block
// with more padding.
#show raw.where(block: true): block.with(
  fill: luma(240),
  inset: 10pt,
  radius: 4pt,
  width: 100%
)

#show: book.with(
  title: "Introduction to GIS Programming",
  subtitle: "A Practical Python Guide to Open Source Geospatial Tools",
  authors: "Qiusheng Wu",
  date: (2025, 01, 12),
  part: "Section",
  chapter: "Chapter",
  cfg: (
    page-cfg: "us-letter",
    margin: (x: 1in, y: 1in),
    font-size: 12pt,
    first-line-indent: 0em,
    par-margin: 1em,
    numbering-style: (
      "{1:I}:\n",
      "{2:1}.\n",
      "{2:1}.{3:1}.\n",
      "{2:1}.{3:1}.{4:1}.\n",
      "{2:1}.{3:1}.{4:1}.{5:1}.\n",
      "{2:1}.{3:1}.{4:1}.{5:1}.{6:a}.",
  ),
)
)
```
</details>

![Image](https://github.com/user-attachments/assets/79e27c39-0180-4abb-9317-6aa63504285b)



![Image](https://github.com/user-attachments/assets/6e38d498-222f-45d2-8842-6e7240c6c681)

Desired results generated by https://github.com/myst-templates/lapreprint-typst
![Image](https://github.com/user-attachments/assets/6116c54e-2f5c-448c-89b6-5a0b22422e36)

![Image](https://github.com/user-attachments/assets/e472aea8-bc8b-4659-800e-340ecd4c46f4)
